---
- name: Install yum-utils
  become: true
  ansible.builtin.yum:
    name: yum-utils
    state: latest

- name: Add docker repo
  become: true
  shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: Install docker dependencies
  become: true
  ansible.builtin.yum:
    name:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io 
      - docker-buildx-plugin 
      - docker-compose-plugin
    state: present

- name: Start and enable docker
  become: true
  systemd:
    state: started
    enabled: yes
    name: docker