- hosts: 127.0.0.1
  connection: local
  vars:
    ansible_python_interpreter: /usr/local/bin/python3.8
  tasks:

    - name: Get minikube
      get_url:
        url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        dest: /tmp/minikube_install

    - name: Install minikube
      become: true
      shell: install /tmp/minikube_install /usr/local/bin/minikube

    - name: Start minikube
      shell: minikube start

    - name: Get kubectl for minikube
      shell: minikube kubectl -- get po -A

    - name: Setup alias for kubectl
      blockinfile:
        path: ~/.bashrc
        block: "alias kubectl='minikube kubectl -p dev-cluster --'"
        create: true

    - name: Clear clusters
      shell: minikube delete --all

    - name: Setup multi-node cluster
      shell: minikube start --nodes 3 -p dev-cluster

    - name: Test cluster and k8s module
      kubernetes.core.k8s_info:
        kind: Node
      register: nodes

    - name: Print nodes
      debug:
        msg: "{{ nodes }}"
