---

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: passwordprofiles.org.rcbg
spec:
  group: org.rcbg
  scope: Namespaced
  names:
    plural: passwordprofiles
    singular: passwordprofile
    kind: PasswordProfile
    listKind: PasswordProfileList
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                profileName:
                  type: string
                creationTimestamp:
                  type: string
                  format: date-time
                creatorUserId:
                  type: string
                length:
                  type: integer
                  minimum: 1
                numbersAllowed:
                  type: boolean
                uppercaseAllowed:
                  type: boolean
                specialCharsAllowed:
                  type: boolean
                excludedSpecialChars:
                  type: string

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: password-profile-access
rules:
  - apiGroups: ["org.rcbg"]
    resources: ["passwordprofiles"]
    verbs: ["get", "watch", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: password-profile-access-binding
roleRef:
  kind: ClusterRole
  name: password-profile-access
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: cgenerator-svc
    apiGroup: ""
    namespace: generation-service