---
- name: Add yum repository for K8s
  become: true
  blockinfile:
    path: /etc/yum.repos.d/kubernetes.repo
    block: "{{ lookup('ansible.builtin.file', '../files/k8s-repo.txt') }}"
    create: true

- name: Install kubeadm with kubelet
  become: true
  yum:
    state: present
    name:
      - kubelet
      - kubeadm

- name: Enable kubelet
  become: true
  systemd:
    enabled: true
    name: kubelet

- name: Start kubelet
  become: true
  systemd:
    state: started
    name: kubelet

- name: Install kubectl on master
  become: true
  when: inventory_hostname in groups['masters']
  yum:
    state: present
    name: kubectl
