- name: Disable SELinux
  shell: set enforce 0

- name: Setup firewall ports for master
  become: true
  when: inventory_hostname in groups['masters']
  ansible.posix.firewalld:
    permanent: true
    port: "{{ item }}/tcp"
    state: enabled
  loop:
    - 6443
    - 2379
    - 2380
    - 10250
    - 10251
    - 10252

- name: Setup firewall ports for workers
  become: true
  when: inventory_hostname in groups['workers']
  ansible.posix.firewalld:
    permanent: true
    port: "{{ item }}/tcp"
    state: enabled
  loop:
    - 10250
    - 30000

- name: Setup masquerade
  become: true
  ansible.posix.firewalld:
    permanent: true
    masquerade: enable
    state: enabled

- name: Reload firewalld
  become: true
  systemd:
   state: restarted
   name: firewalld

- name: Enable bridge iptables
  become: true
  blockinfile:
    path: /etc/sysctl.d/k8s.conf
    block: "{{ lookup('file', '../files/bridge.txt') }}"
    create: true
